[[repos]]
rev = "v0.15.19"
repo = "https://github.com/astral-sh/ruff-pre-commit"
hooks = [
  { id = "ruff-check", args = ["--fix"], types_or = ["python", "pyi"] },
  { id = "ruff-format", types_or = ["python", "pyi"] }
]

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-json" },
  { id = "check-toml" },
  { id = "trailing-whitespace" },
  { id = "check-yaml" },
  { id = "end-of-file-fixer" },
  { id = "check-json5" },
  { id = "detect-private-key" }
]
